export const rats = {
  'razor-whisker': {
    id: 'razor-whisker',
    displayName: 'Razor Whisker',
    handle: '@razorwhisker',
    type: 'Market Hotel show kid',
    voice: 'Earnest, bass-response-of-the-floor',
    selfiePath: 'assets/selfies/razor-whisker.webp',
  },
  'dj-nibblers': {
    id: 'dj-nibblers',
    displayName: 'DJ Nibblers',
    handle: '@djnibblers',
    type: 'The cocaine rat',
    voice: 'Manic, run-on, "i only do diet"',
    selfiePath: 'assets/selfies/dj-nibblers.webp',
  },
  'pinky-mae': {
    id: 'pinky-mae',
    displayName: 'Pinky Mae Pellet',
    handle: '@pinkymae',
    type: "Influencer-rat (in both senses — she's spreading influenza)",
    voice: 'Lowercase, hashtags, lighting notes, occasional sniffles',
    selfiePath: 'assets/selfies/pinky-mae.webp',
  },
  'old-cheese': {
    id: 'old-cheese',
    displayName: 'Old Cheese',
    handle: '@oldcheese',
    type: 'Pre-gentrification longtime resident',
    voice: "Sad, accusatory, references the Bristol Room and Trommer's Brewery",
    selfiePath: 'assets/selfies/old-cheese.webp',
  },
  'tabitha-von-wyckoff': {
    id: 'tabitha-von-wyckoff',
    displayName: 'Tabitha von Wyckoff',
    handle: '@tabithavonwyckoff',
    type: 'Yelp Elite gentrifier from Manhattan',
    voice: 'Performative authenticity',
    selfiePath: 'assets/selfies/tabitha-von-wyckoff.webp',
  },
  'comrade-crumb': {
    id: 'comrade-crumb',
    displayName: 'Comrade Crumb',
    handle: '@comradecrumb',
    type: 'Wystan Pemberton-Whitford III, CT nepo socialist',
    voice: 'DSA-Twitter cadence with reveals',
    selfiePath: 'assets/selfies/comrade-crumb.webp',
  },
  'mira-wong-witherspoon': {
    id: 'mira-wong-witherspoon',
    displayName: 'Mira Wong-Witherspoon',
    handle: '@mirawongwitherspoon',
    type: 'Wasian, gets it from both sides',
    voice: 'Self-aware, ambivalent',
    selfiePath: 'assets/selfies/mira-wong-witherspoon.webp',
  },
  'wyckoff-six': {
    id: 'wyckoff-six',
    displayName: 'The Wyckoff Six',
    handle: '@wyckoffsix',
    type: 'Six-rat polycule, co-signed reviews',
    voice: '"We," processed, four-hour debriefs',
    selfiePath: 'assets/selfies/wyckoff-six.webp',
  },
  'vintage-vermin': {
    id: 'vintage-vermin',
    displayName: 'Vintage Vermin',
    handle: '@vintagevermin',
    type: 'Thrifter / curator',
    voice: 'Aesthetic-era reviews of trash',
    selfiePath: 'assets/selfies/vintage-vermin.webp',
  },
  'edible-eddie': {
    id: 'edible-eddie',
    displayName: 'Edible Eddie',
    handle: '@edibleeddie',
    type: 'Wrong-edible casualty',
    voice: 'Time-distorted, repetitive, glitching',
    selfiePath: 'assets/selfies/edible-eddie.webp',
  },
  'rosemary-rib': {
    id: 'rosemary-rib',
    displayName: 'Rosemary Rib',
    handle: '@rosemaryrib',
    type: 'Performance artist who took over Caffeine Underground',
    voice: 'Durational, the venue is the piece',
    selfiePath: 'assets/selfies/rosemary-rib.webp',
  },
};
