#!/usr/bin/env python3
"""
scripts/analyze_usv_features.py

Regenerates src/audio/usv-features.js — per-sample acoustic features
consumed by the syllabic voice mode (rat-generator.js):

  eff     effective duration in seconds (RMS envelope above -30 dBFS
          relative to peak, first active frame to last)
  onset   seconds of lead-in before the envelope crosses threshold
  contour flat | rise | fall | trill, from the dominant-frequency
          track (STFT, 1.5-10 kHz band — the extractor's bandpass)

Run whenever bank audio changes (after generate-audio-manifest.js):

    python3 scripts/analyze_usv_features.py

Needs numpy + scipy and ffmpeg on PATH.
"""

import json
import os
import subprocess

import numpy as np
from scipy.signal import stft

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
BANKS = {
    "usvs": "assets/sounds/usvs",
    "usvs-cocaine": "assets/sounds/usvs-cocaine",
}
OUT = os.path.join(ROOT, "src/audio/usv-features.js")

SR = 44100
FRAME_MS = 10
ACTIVE_DB = -30  # matches extract_squeaks.py's gate threshold
BAND = (1500, 10000)


def decode(path):
    out = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", path, "-f", "f32le", "-ac", "1",
         "-ar", str(SR), "-"],
        capture_output=True, check=True,
    ).stdout
    return np.frombuffer(out, dtype=np.float32)


def analyze(path):
    x = decode(path)
    n = len(x)
    peak = np.max(np.abs(x)) or 1.0

    frame = int(SR * FRAME_MS / 1000)
    nf = n // frame
    rms = np.sqrt(np.mean(x[: nf * frame].reshape(nf, frame) ** 2, axis=1))
    thr = peak * (10 ** (ACTIVE_DB / 20))
    active = np.where(rms > thr)[0]
    if len(active) == 0:
        return None
    t0 = active[0] * FRAME_MS / 1000
    t1 = (active[-1] + 1) * FRAME_MS / 1000

    seg = x[int(t0 * SR): int(t1 * SR)]
    nper = 1024
    if len(seg) < nper:
        seg = np.pad(seg, (0, nper - len(seg)))
    f, _, Z = stft(seg, fs=SR, nperseg=nper, noverlap=nper // 2)
    mag = np.abs(Z)
    band = (f >= BAND[0]) & (f <= BAND[1])
    mag_b = mag[band]
    f_b = f[band]
    fr_energy = mag_b.sum(axis=0)
    keep = fr_energy > 0.1 * fr_energy.max()
    if keep.sum() < 2:
        keep = np.ones_like(keep, dtype=bool)
    dom = f_b[np.argmax(mag_b[:, keep], axis=0)]

    tt = np.linspace(0, 1, len(dom))
    slope = np.polyfit(tt, dom, 1)[0] if len(dom) > 1 else 0.0
    dif = np.diff(dom)
    flips = int(np.sum(np.abs(np.diff(np.sign(dif[np.abs(dif) > 50]))) > 0))
    fm_range = float(dom.max() - dom.min())

    if flips >= 4 and fm_range > 800:
        contour = "trill"
    elif slope > 600:
        contour = "rise"
    elif slope < -600:
        contour = "fall"
    else:
        contour = "flat"

    return {
        "eff": round(t1 - t0, 3),
        "onset": round(t0, 3),
        "contour": contour,
    }


def main():
    features = {}
    for bank, rel in BANKS.items():
        d = os.path.join(ROOT, rel)
        rows = {}
        for fn in sorted(os.listdir(d)):
            if not fn.endswith(".webm"):
                continue
            r = analyze(os.path.join(d, fn))
            if r:
                rows[fn] = r
        features[bank] = rows
        print(f"{bank}: {len(rows)} samples analyzed")

    body = json.dumps(features, indent=2, sort_keys=True)
    with open(OUT, "w") as fh:
        fh.write(
            "// Generated by scripts/analyze_usv_features.py — do not edit"
            " by hand.\n"
            "// Re-run that script when bank audio changes.\n"
            "// eff: effective duration (s), onset: lead-in (s),\n"
            "// contour: flat | rise | fall | trill.\n\n"
            f"export const USV_FEATURES = {body};\n"
        )
    print(f"Wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
